# Generated by Django 2.2.17 on 2020-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0005_auto_20201206_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choice_list',
            field=models.ManyToManyField(through='infotinder.ChoiceList', to='infotinder.StartUp'),
        ),
    ]
