# Generated by Django 2.2.17 on 2020-12-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0006_auto_20201206_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='important_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_list',
            field=models.ManyToManyField(through='infotinder.ChoiceList', to='infotinder.StartUp'),
        ),
    ]
