# Generated by Django 2.2.17 on 2020-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0007_auto_20201206_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_list',
            field=models.ManyToManyField(through='infotinder.ChoiceList', to='infotinder.StartUp'),
        ),
    ]
