# Generated by Django 2.2.17 on 2020-12-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0008_auto_20201207_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choicelist',
            new_name='StartUpUser',
        ),
    ]
