# Generated by Django 2.2.17 on 2020-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0009_auto_20201207_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Инвестор', 'Инвестор'), ('Пользователь', 'Пользователь')], default='Инвестор', max_length=20),
        ),
    ]
