# Generated by Django 2.2.17 on 2020-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0011_user_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='organization_types',
            field=models.CharField(choices=[('Fund', 'Фонд'), ('Company', 'Компания'), ('Private', 'Частное лицо')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
