# Generated by Django 2.2.17 on 2020-12-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0012_auto_20201215_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_types',
            field=models.CharField(choices=[('Фонд', 'Фонд'), ('Компания', 'Компания'), ('Частное лицо', 'Частное лицо')], max_length=10),
        ),
    ]
