# Generated by Django 2.2.17 on 2020-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotinder', '0013_auto_20201215_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_types',
            field=models.CharField(choices=[('Fund', 'Фонд'), ('Company', 'Компания'), ('Private', 'Частное лицо')], max_length=15),
        ),
    ]
